[master]
master-node ansible_host=10.172.13.222 ansible_user=master

[workers]
worker-node ansible_host=10.172.13.200 ansible_user=blagoy

[cluster:children]
master
workers

[gpu_nodes:children]
master
# Add worker hostnames here as well when they have GPUs
